# Generated by Django 4.2.7 on 2025-12-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/lessons/', verbose_name='audio file'),
        ),
    ]
