# Generated by Django 4.2.7 on 2025-12-12 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('text', 'Text'), ('quiz', 'Quiz')], default='audio', max_length=10, verbose_name='lesson type'),
        ),
        migrations.CreateModel(
            name='LessonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='courses/lessons/media/', verbose_name='media file')),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10, verbose_name='media type')),
                ('title', models.CharField(blank=True, help_text='Optional title for this media file', max_length=255, verbose_name='title')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='duration (seconds)')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='file size (bytes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'lesson media',
                'verbose_name_plural': 'lesson media',
                'ordering': ['lesson', 'order'],
                'indexes': [models.Index(fields=['lesson', 'order'], name='courses_les_lesson__9b7a45_idx')],
            },
        ),
    ]
