# Generated by Django 4.2.7 on 2025-12-18 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_lesson_lesson_type_lessonmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='file size (bytes)')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='downloaded at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'download',
                'verbose_name_plural': 'downloads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='courses_dow_user_id_487e2a_idx'), models.Index(fields=['status'], name='courses_dow_status_2d5907_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='certificate number')),
                ('verification_code', models.CharField(max_length=50, unique=True, verbose_name='verification code')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='certificate file')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='issued date')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['student', '-issued_date'], name='courses_cer_student_621677_idx'), models.Index(fields=['certificate_number'], name='courses_cer_certifi_b5881b_idx'), models.Index(fields=['verification_code'], name='courses_cer_verific_ead7dc_idx')],
            },
        ),
    ]
