# Generated by Django 5.2.9 on 2026-01-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_created_by_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#667eea', help_text='Hex color code for UI', max_length=7, verbose_name='color code'),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first', verbose_name='display order'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for main category, select a category to create subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS icon class (e.g., fas fa-code)', max_length=50, verbose_name='icon class'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent')},
        ),
    ]
