# Generated by Django 5.2.9 on 2026-01-15 09:35

from django.db import migrations
from django.utils.text import slugify


def populate_lesson_slugs(apps, schema_editor):
    """Generate unique slugs for all existing lessons"""
    Lesson = apps.get_model('courses', 'Lesson')
    
    for lesson in Lesson.objects.all():
        if not lesson.slug:
            base_slug = slugify(lesson.title)
            slug = base_slug
            counter = 1
            
            # Ensure uniqueness within the same course
            while Lesson.objects.filter(course=lesson.course, slug=slug).exclude(pk=lesson.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            lesson.slug = slug
            lesson.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """Reverse migration - clear all slugs"""
    Lesson = apps.get_model('courses', 'Lesson')
    Lesson.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_lesson_slug'),
    ]

    operations = [
        migrations.RunPython(populate_lesson_slugs, reverse_populate_slugs),
    ]
