# Generated by Django 5.2.9 on 2026-01-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_populate_lesson_slugs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'slug'], name='courses_les_course__c95c5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='unique_lesson_slug_per_course'),
        ),
    ]
