# Generated by Django 4.2.7 on 2026-02-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_add_lesson_slug_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='Extracted YouTube video ID for embedding', max_length=20, verbose_name='YouTube video ID'),
        ),
    ]
