# Generated by Django 5.2.9 on 2026-02-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_add_youtube_video_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='Extracted YouTube video ID', max_length=20, verbose_name='YouTube video ID'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='YouTube video link for this lesson', verbose_name='YouTube video URL'),
        ),
    ]
