# Generated by Django 5.2.9 on 2026-02-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lesson_youtube_video_id_lesson_youtube_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='youtube_video_id',
        ),
    ]
