# Generated by Django 4.2.7 on 2025-12-16 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_alter_lesson_lesson_type_lessonmedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('total_users', models.IntegerField(default=0, verbose_name='total users')),
                ('total_teachers', models.IntegerField(default=0, verbose_name='total teachers')),
                ('total_students', models.IntegerField(default=0, verbose_name='total students')),
                ('total_courses', models.IntegerField(default=0, verbose_name='total courses')),
                ('published_courses', models.IntegerField(default=0, verbose_name='published courses')),
                ('pending_approval_courses', models.IntegerField(default=0, verbose_name='pending approval')),
                ('total_enrollments', models.IntegerField(default=0, verbose_name='total enrollments')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total revenue')),
                ('completed_transactions', models.IntegerField(default=0, verbose_name='completed transactions')),
                ('failed_transactions', models.IntegerField(default=0, verbose_name='failed transactions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'dashboard stat',
                'verbose_name_plural': 'dashboard stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=False, help_text='Is this setting visible to public?', verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'platform setting',
                'verbose_name_plural': 'platform settings',
            },
        ),
        migrations.CreateModel(
            name='CourseApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], default='pending', max_length=20, verbose_name='status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_comments', models.TextField(blank=True, verbose_name='review comments')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='courses.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course approval',
                'verbose_name_plural': 'course approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('suspend', 'Suspend'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('refund', 'Refund'), ('other', 'Other')], max_length=20, verbose_name='action')),
                ('content_type', models.CharField(max_length=100, verbose_name='content type')),
                ('object_id', models.CharField(max_length=255, verbose_name='object ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='object representation')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='old values')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='new values')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin log',
                'verbose_name_plural': 'admin logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='platformadm_admin_i_5dea2b_idx'), models.Index(fields=['action', '-created_at'], name='platformadm_action_748d82_idx'), models.Index(fields=['content_type', 'object_id'], name='platformadm_content_2e2725_idx')],
            },
        ),
    ]
