# Generated by Django 4.2.7 on 2025-12-16 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platformadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('content_moderator', 'Content Moderator'), ('finance_admin', 'Finance Admin'), ('user_support', 'User Support'), ('analytics_viewer', 'Analytics Viewer'), ('platform_admin', 'Platform Admin')], default='platform_admin', max_length=30, verbose_name='admin role')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin role',
                'verbose_name_plural': 'admin roles',
            },
        ),
    ]
