# Generated by Django 5.2.9 on 2026-01-12 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_created_by_alter_course_teacher'),
        ('platformadmin', '0003_faq_videosettings_referralprogram_cmspage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='assigned', max_length=20, verbose_name='status')),
                ('can_edit_content', models.BooleanField(default=True, help_text='Allow teacher to upload/edit lessons and modules', verbose_name='can edit content')),
                ('can_edit_details', models.BooleanField(default=False, help_text='Allow teacher to edit course title, description, pricing', verbose_name='can edit course details')),
                ('can_publish', models.BooleanField(default=False, help_text='Allow teacher to publish/unpublish course', verbose_name='can publish')),
                ('assignment_notes', models.TextField(blank=True, help_text='Admin notes about this assignment', verbose_name='assignment notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='rejected at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course assignment',
                'verbose_name_plural': 'course assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['teacher', 'status'], name='platformadm_teacher_4d5185_idx'), models.Index(fields=['course', 'status'], name='platformadm_course__14095e_idx'), models.Index(fields=['-assigned_at'], name='platformadm_assigne_55b070_idx')],
                'unique_together': {('course', 'teacher')},
            },
        ),
    ]
