# Generated by Django 5.2.9 on 2026-01-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0004_courseassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='can_delete_content',
            field=models.BooleanField(default=False, help_text='Allow teacher to delete lessons and modules', verbose_name='can delete content'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='can_edit_content',
            field=models.BooleanField(default=True, help_text='Allow teacher to add and edit lessons and modules', verbose_name='can edit content'),
        ),
    ]
