# Generated by Django 4.2.7 on 2026-01-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0005_commission_and_coupon_features'),
        ('platformadmin', '0005_courseassignment_can_delete_content_and_more'),
    ]

    operations = [
    ]
