# Generated by Django 5.2.9 on 2026-01-22 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0006_merge_20260120_1023'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Platform commission percentage for this teacher on this course (leave empty to use platform default)', max_digits=5, null=True, verbose_name='commission percentage'),
        ),
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid out in this transaction', max_digits=10, verbose_name='payout amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(blank=True, help_text='e.g., Bank Transfer, UPI, etc.', max_length=100, verbose_name='payment method')),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank transaction ID or reference number', max_length=255, verbose_name='transaction reference')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('processed_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payout_transactions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payout transaction',
                'verbose_name_plural': 'payout transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', '-created_at'], name='platformadm_teacher_3e0b0c_idx'), models.Index(fields=['status', '-created_at'], name='platformadm_status_6a6c4e_idx'), models.Index(fields=['-created_at'], name='platformadm_created_af571c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total commission earned from all course purchases', max_digits=12, verbose_name='total earned')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount already paid to teacher', max_digits=12, verbose_name='total paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_payout_at', models.DateTimeField(blank=True, null=True, verbose_name='last payout at')),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='commission_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher commission',
                'verbose_name_plural': 'teacher commissions',
                'ordering': ['-total_earned'],
                'indexes': [models.Index(fields=['teacher'], name='platformadm_teacher_64bbaa_idx'), models.Index(fields=['-total_earned'], name='platformadm_total_e_ca93ad_idx')],
            },
        ),
    ]
