# Generated by Django 5.2.9 on 2026-02-03 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0007_alter_courseassignment_commission_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='If inactive, user loses free access', verbose_name='active')),
                ('reason', models.TextField(blank=True, help_text='Admin notes about why this user has free access', verbose_name='reason for free access')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty for unlimited access', null=True, verbose_name='expires at')),
                ('max_courses', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited courses', null=True, verbose_name='max courses')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_free_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='free_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'free user',
                'verbose_name_plural': 'free users',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='platformadm_user_id_b66b1f_idx'), models.Index(fields=['is_active', '-assigned_at'], name='platformadm_is_acti_271aa5_idx')],
            },
        ),
    ]
