# Generated by Django 5.2.9 on 2026-02-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0010_ensure_teammember_table'),
        ('platformadmin', '0010_teammember_footersettings_pagecontent'),
    ]

    operations = [
    ]
