# Generated by Django 5.2.9 on 2026-02-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0010_teammember_footersettings_pagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'team member', 'verbose_name_plural': 'team members'},
        ),
    ]
