# Generated by Django 5.2.9 on 2026-02-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0010_ensure_teammember_table'),
        ('platformadmin', '0010_pagecontent_footersettings'),
    ]

    operations = [
    ]
