# Generated by Django 5.2.9 on 2026-02-14 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0011_merge_20260214_1519'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=150, verbose_name='name')),
                ('designation', models.CharField(help_text='Job title or role', max_length=150, verbose_name='designation')),
                ('subject', models.CharField(help_text='Area of expertise or subject focus', max_length=200, verbose_name='subject/expertise')),
                ('experience', models.CharField(help_text="Years of experience (e.g., '5 years', '10+ years')", max_length=100, verbose_name='experience')),
                ('photo', models.ImageField(help_text='Team member photo (recommended: 400x400px)', upload_to='team_members/', verbose_name='photo')),
                ('bio', models.TextField(blank=True, help_text='Short biography or description', verbose_name='biography')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('is_active', models.BooleanField(default=True, help_text='Display on About Us page', verbose_name='is active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of appearance (lower numbers first)', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_members', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team member',
                'verbose_name_plural': 'team members',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
