# Generated by Django 5.2.9 on 2026-02-11 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0011_merge_20260211_0958'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('designation', models.CharField(help_text='e.g., CEO, Lead Instructor, etc.', max_length=200, verbose_name='designation')),
                ('subject', models.CharField(blank=True, help_text='Subject area or expertise', max_length=200, verbose_name='subject/expertise')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('photo', models.ImageField(help_text='Recommended size: 400x400 pixels. Image will be resized to fit.', upload_to='team_members/', verbose_name='profile photo')),
                ('bio', models.TextField(blank=True, help_text='Short bio about the team member', verbose_name='biography')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'team member',
                'verbose_name_plural': 'team members',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='platformadm_is_acti_70c4f0_idx')],
            },
        ),
    ]
