# Generated by Django 5.2.9 on 2026-02-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0012_teammember_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='years_of_experience',
        ),
    ]
