# Generated by Django 5.2.9 on 2026-02-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0013_remove_teammember_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='years of experience'),
        ),
    ]
