# Generated by Django 4.2.7 on 2026-02-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0010_ensure_teammember_table'),
        ('platformadmin', '0014_teammember_years_of_experience'),
    ]

    operations = [
    ]
