# Generated by Django - Data migration to fix NULL experience values

from django.db import migrations


def fix_null_experience(apps, schema_editor):
    """Update NULL experience values to empty string"""
    TeamMember = apps.get_model('platformadmin', 'TeamMember')
    TeamMember.objects.filter(experience__isnull=True).update(experience='')


def reverse_fix(apps, schema_editor):
    """No reverse operation needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0017_merge_20260211_0043'),
    ]

    operations = [
        migrations.RunPython(fix_null_experience, reverse_fix),
    ]
