# Generated by Django 5.2.9 on 2026-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0018_fix_null_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='experience',
            field=models.CharField(blank=True, default='', help_text="Years of experience (e.g., '5 years', '10+ years')", max_length=100, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Display on Teams page', verbose_name='is active'),
        ),
    ]
