# Generated by Django 5.2.9 on 2026-02-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0019_teammember_email_teammember_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='experience',
            field=models.CharField(blank=True, default='', help_text="Years of experience (e.g., '5 years', '10+ years')", max_length=100, verbose_name='experience'),
        ),
    ]
