# Generated by Django 4.2.7 on 2025-12-10 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], max_length=20, verbose_name='payment method')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Razorpay order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, verbose_name='Razorpay payment ID')),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, verbose_name='Razorpay signature')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('notes', models.JSONField(blank=True, default=dict, verbose_name='notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('payment.authorized', 'Payment Authorized'), ('payment.captured', 'Payment Captured'), ('payment.failed', 'Payment Failed'), ('order.paid', 'Order Paid'), ('refund.created', 'Refund Created'), ('subscription.activated', 'Subscription Activated'), ('subscription.charged', 'Subscription Charged'), ('subscription.cancelled', 'Subscription Cancelled'), ('subscription.completed', 'Subscription Completed'), ('subscription.paused', 'Subscription Paused'), ('subscription.resumed', 'Subscription Resumed')], max_length=50, verbose_name='event type')),
                ('razorpay_event_id', models.CharField(max_length=255, unique=True, verbose_name='Razorpay event ID')),
                ('payload', models.JSONField(verbose_name='payload')),
                ('is_processed', models.BooleanField(default=False, verbose_name='processed')),
                ('processing_error', models.TextField(blank=True, verbose_name='processing error')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'payment webhook',
                'verbose_name_plural': 'payment webhooks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='refund amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('reason', models.CharField(choices=[('not_satisfied', 'Not Satisfied'), ('technical_issue', 'Technical Issue'), ('duplicate_payment', 'Duplicate Payment'), ('course_cancelled', 'Course Cancelled'), ('other', 'Other')], max_length=30, verbose_name='reason')),
                ('reason_description', models.TextField(blank=True, verbose_name='reason description')),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=255, verbose_name='Razorpay refund ID')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='status')),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='billing interval')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='currency')),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Razorpay subscription ID')),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=255, verbose_name='Razorpay plan ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('next_billing_date', models.DateTimeField(blank=True, null=True, verbose_name='next billing date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='courses.course')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
