# Generated by Django 4.2.7 on 2025-12-17 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_lesson_lesson_type_lessonmedia'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='coupon code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount for percentage type', max_digits=10, null=True, verbose_name='max discount amount')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='minimum purchase')),
                ('valid_from', models.DateTimeField(verbose_name='valid from')),
                ('valid_until', models.DateTimeField(verbose_name='valid until')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20, verbose_name='status')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Total uses allowed, null for unlimited', null=True, verbose_name='max uses')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='max uses per user')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='current uses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Leave empty for all categories', related_name='coupons', to='courses.category')),
                ('applicable_courses', models.ManyToManyField(blank=True, help_text='Leave empty for all courses', related_name='coupons', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='original amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount amount')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='final amount')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='used at')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.coupon')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'coupon usage',
                'verbose_name_plural': 'coupon usages',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['coupon', '-used_at'], name='payments_co_coupon__4d0825_idx'), models.Index(fields=['user', '-used_at'], name='payments_co_user_id_2910a0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='payments_co_code_2829d0_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status', '-created_at'], name='payments_co_status_f6be47_idx'),
        ),
    ]
