# Generated by Django 5.2.9 on 2026-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_coupon_couponusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='encrypted_bank_name',
            field=models.CharField(blank=True, help_text='Encrypted bank name for netbanking', max_length=500, verbose_name='encrypted bank name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='encrypted_card_last4',
            field=models.CharField(blank=True, help_text='Encrypted last 4 digits of card', max_length=500, verbose_name='encrypted card last 4 digits'),
        ),
        migrations.AddField(
            model_name='payment',
            name='encrypted_card_type',
            field=models.CharField(blank=True, help_text='Encrypted card type (Visa, Mastercard, etc.)', max_length=500, verbose_name='encrypted card type'),
        ),
        migrations.AddField(
            model_name='payment',
            name='encrypted_upi_id',
            field=models.CharField(blank=True, help_text='Encrypted UPI ID', max_length=500, verbose_name='encrypted UPI ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='encrypted_wallet_name',
            field=models.CharField(blank=True, help_text='Encrypted wallet name', max_length=500, verbose_name='encrypted wallet name'),
        ),
    ]
