# Generated by Django 5.2.9 on 2026-02-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_coupon_commission_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount after deducting Razorpay fee and GST (used for commission split)', max_digits=10, verbose_name='net amount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='2% transaction fee charged by Razorpay', max_digits=10, verbose_name='Razorpay fee'),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='18% GST on Razorpay transaction fee', max_digits=10, verbose_name='GST on Razorpay fee'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='extra_commission_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra commission from using this coupon (equals coupon discount %)', max_digits=10, verbose_name='extra commission earned'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Gross amount paid by user', max_digits=10, verbose_name='amount'),
        ),
    ]
