# Generated by Django 4.2.7 on 2025-12-10 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('playback_duration', models.PositiveIntegerField(default=0, help_text='How long the audio was played', verbose_name='playback duration (seconds)')),
                ('completed', models.BooleanField(default=False, help_text='Did user listen to end?', verbose_name='completed')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='accessed at')),
            ],
            options={
                'verbose_name': 'audio access log',
                'verbose_name_plural': 'audio access logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('file_path', models.CharField(help_text='Path in R2/storage', max_length=500, verbose_name='file path')),
                ('file_format', models.CharField(choices=[('mp3', 'MP3'), ('m4a', 'M4A'), ('wav', 'WAV'), ('aac', 'AAC')], max_length=10, verbose_name='file format')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='file size (bytes)')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='duration (seconds)')),
                ('bitrate', models.PositiveIntegerField(blank=True, default=0, verbose_name='bitrate (kbps)')),
                ('sample_rate', models.PositiveIntegerField(blank=True, default=0, verbose_name='sample rate (Hz)')),
                ('channels', models.PositiveSmallIntegerField(blank=True, default=2, verbose_name='channels')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('access_key', models.CharField(blank=True, max_length=100, unique=True, verbose_name='access key')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='last accessed')),
            ],
            options={
                'verbose_name': 'audio file',
                'verbose_name_plural': 'audio files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('upload', 'Upload'), ('transcode', 'Transcode'), ('extract_metadata', 'Extract Metadata'), ('generate_waveform', 'Generate Waveform')], max_length=30, verbose_name='task type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery task ID')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='progress')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_tasks', to='audio.audiofile')),
            ],
            options={
                'verbose_name': 'audio processing task',
                'verbose_name_plural': 'audio processing tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
