# Generated by Django 4.2.7 on 2025-12-10 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_audio_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audioaccesslog',
            name='audio_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='audio.audiofile'),
        ),
        migrations.AddField(
            model_name='audioaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['uploaded_by', 'status'], name='audio_audio_uploade_933c13_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['status', '-created_at'], name='audio_audio_status_4a5146_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['access_key'], name='audio_audio_access__3fcc34_idx'),
        ),
        migrations.AddIndex(
            model_name='audioaccesslog',
            index=models.Index(fields=['audio_file', '-accessed_at'], name='audio_audio_audio_f_8bb1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='audioaccesslog',
            index=models.Index(fields=['user', '-accessed_at'], name='audio_audio_user_id_8e44cc_idx'),
        ),
    ]
