# Generated by Django 4.2.7 on 2025-12-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('category', models.CharField(choices=[('general', 'General'), ('courses', 'Courses'), ('payments', 'Payments'), ('technical', 'Technical'), ('account', 'Account')], default='general', max_length=20, verbose_name='category')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='show in footer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Audio Learning Platform', max_length=100, verbose_name='site name')),
                ('site_tagline', models.CharField(blank=True, max_length=255, verbose_name='tagline')),
                ('site_description', models.TextField(blank=True, verbose_name='description')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='support email')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('enable_registration', models.BooleanField(default=True, verbose_name='enable registration')),
                ('enable_payments', models.BooleanField(default=True, verbose_name='enable payments')),
                ('enable_reviews', models.BooleanField(default=True, verbose_name='enable reviews')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='enable notifications')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='maintenance message')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='meta keywords')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
