# Generated by Django 4.2.7 on 2025-12-17 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(help_text='Banner message content', verbose_name='message')),
                ('banner_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('promo', 'Promotion')], default='info', max_length=20, verbose_name='banner type')),
                ('cta_text', models.CharField(blank=True, help_text='Call-to-action button text', max_length=100, verbose_name='CTA text')),
                ('cta_link', models.URLField(blank=True, help_text='Link for the CTA button', verbose_name='CTA link')),
                ('image', models.ImageField(blank=True, help_text='Optional banner background image', null=True, upload_to='banners/', verbose_name='banner image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('show_on_web', models.BooleanField(default=True, verbose_name='show on web')),
                ('show_on_mobile', models.BooleanField(default=True, verbose_name='show on mobile')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority banners show first', verbose_name='priority')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiration', null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
