# Generated by assistant to align Banner model changes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_banner'),
    ]

    operations = [
        # Rename old field names to new names
        migrations.RenameField(
            model_name='banner',
            old_name='message',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='cta_text',
            new_name='button_text',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='cta_link',
            new_name='button_link',
        ),
        # Remove fields that were dropped from the model
        migrations.RemoveField(
            model_name='banner',
            name='show_on_web',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='show_on_mobile',
        ),
    ]
