# Generated by Django 4.2.7 on 2025-12-18 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_update_banner_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('home', 'Home Page'), ('course', 'Course Page'), ('offer', 'Special Offer')], default='home', help_text='Where should this banner be displayed?', max_length=20, verbose_name='banner type'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, help_text='URL or path for the CTA button', max_length=500, verbose_name='button link'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, help_text='Text for the CTA button (e.g., "Enroll Now", "Learn More")', max_length=100, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(help_text='Banner description/message', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='', help_text='Banner image (recommended: 1920x600px)', upload_to='banners/%Y/%m/', verbose_name='banner image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive banners are not displayed', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher priority banners appear first (0-100)', verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Banner becomes active from this date', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Banner title/headline', max_length=200, verbose_name='title'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='common_bann_is_acti_d6abb2_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['banner_type', 'priority'], name='common_bann_banner__54cf8d_idx'),
        ),
    ]
