# Generated by Django 4.2.7 on 2025-12-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='daily_goal_minutes',
            field=models.IntegerField(default=30, help_text='Target learning minutes per day', verbose_name='daily goal (minutes)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weekly_goal_hours',
            field=models.IntegerField(default=5, help_text='Target learning hours per week', verbose_name='weekly goal (hours)'),
        ),
    ]
