# Generated by Django 4.2.7 on 2025-12-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_daily_goal_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='auto_play_next',
            field=models.BooleanField(default=True, verbose_name='auto play next'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='download_quality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=20, verbose_name='download quality'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='email notifications'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='app language'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='notifications enabled'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='playback_speed',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Audio playback speed (0.5 to 2.0)', max_digits=3, verbose_name='playback speed'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='push notifications'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10, verbose_name='theme'),
        ),
    ]
