# Generated by Django 4.2.7 on 2025-12-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.IntegerField(default=0, verbose_name='total enrollments')),
                ('active_enrollments', models.IntegerField(default=0, verbose_name='active enrollments')),
                ('completed_enrollments', models.IntegerField(default=0, verbose_name='completed enrollments')),
                ('dropout_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='dropout rate')),
                ('total_listening_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total listening hours')),
                ('avg_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avg completion rate')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='total sessions')),
                ('avg_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='avg session duration (min)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total revenue')),
                ('avg_revenue_per_student', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='avg revenue per student')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='total reviews')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='average rating')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='last calculated')),
            ],
            options={
                'verbose_name': 'course analytics',
                'verbose_name_plural': 'course analytics',
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('total_active_users', models.IntegerField(default=0, verbose_name='total active users')),
                ('new_users', models.IntegerField(default=0, verbose_name='new users')),
                ('total_students', models.IntegerField(default=0, verbose_name='total students')),
                ('total_teachers', models.IntegerField(default=0, verbose_name='total teachers')),
                ('total_courses', models.IntegerField(default=0, verbose_name='total courses')),
                ('new_courses', models.IntegerField(default=0, verbose_name='new courses')),
                ('total_lessons', models.IntegerField(default=0, verbose_name='total lessons')),
                ('total_enrollments', models.IntegerField(default=0, verbose_name='total enrollments')),
                ('new_enrollments', models.IntegerField(default=0, verbose_name='new enrollments')),
                ('active_enrollments', models.IntegerField(default=0, verbose_name='active enrollments')),
                ('total_listening_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total listening hours')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='total sessions')),
                ('avg_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='avg session duration (min)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total revenue')),
                ('total_payments', models.IntegerField(default=0, verbose_name='total payments')),
                ('successful_payments', models.IntegerField(default=0, verbose_name='successful payments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'daily analytics',
                'verbose_name_plural': 'daily analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='session ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='duration (seconds)')),
                ('start_position', models.PositiveIntegerField(default=0, verbose_name='start position (seconds)')),
                ('end_position', models.PositiveIntegerField(default=0, verbose_name='end position (seconds)')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='device type')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='browser')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
            ],
            options={
                'verbose_name': 'listening session',
                'verbose_name_plural': 'listening sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrollments', models.IntegerField(default=0, verbose_name='total enrollments')),
                ('active_enrollments', models.IntegerField(default=0, verbose_name='active enrollments')),
                ('completed_courses', models.IntegerField(default=0, verbose_name='completed courses')),
                ('total_listening_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total listening hours')),
                ('total_lessons_completed', models.IntegerField(default=0, verbose_name='total lessons completed')),
                ('avg_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avg completion rate')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='total sessions')),
                ('avg_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='avg session duration (min)')),
                ('total_notes', models.IntegerField(default=0, verbose_name='total notes')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='last active')),
                ('current_streak', models.IntegerField(default=0, verbose_name='current streak (days)')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='longest streak (days)')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total spent')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='last calculated')),
            ],
            options={
                'verbose_name': 'student analytics',
                'verbose_name_plural': 'student analytics',
            },
        ),
        migrations.CreateModel(
            name='TeacherAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_courses', models.IntegerField(default=0, verbose_name='total courses')),
                ('published_courses', models.IntegerField(default=0, verbose_name='published courses')),
                ('total_lessons', models.IntegerField(default=0, verbose_name='total lessons')),
                ('total_students', models.IntegerField(default=0, verbose_name='total students')),
                ('active_students', models.IntegerField(default=0, verbose_name='active students')),
                ('total_listening_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total listening hours')),
                ('avg_course_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='avg course rating')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='total reviews')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total revenue')),
                ('avg_revenue_per_course', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='avg revenue per course')),
                ('last_calculated', models.DateTimeField(auto_now=True, verbose_name='last calculated')),
            ],
            options={
                'verbose_name': 'teacher analytics',
                'verbose_name_plural': 'teacher analytics',
            },
        ),
    ]
