# Generated by Django 4.2.7 on 2025-12-10 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheranalytics',
            name='teacher',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanalytics',
            name='student',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseanalytics',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseanalytics',
            name='most_popular_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.lesson'),
        ),
        migrations.AddIndex(
            model_name='listeningsession',
            index=models.Index(fields=['user', '-started_at'], name='analytics_l_user_id_c453fd_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningsession',
            index=models.Index(fields=['lesson', '-started_at'], name='analytics_l_lesson__76a5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningsession',
            index=models.Index(fields=['-started_at'], name='analytics_l_started_172492_idx'),
        ),
    ]
