# Generated by Django 4.2.7 on 2025-12-10 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='to email')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('template_type', models.CharField(blank=True, max_length=50, verbose_name='template type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('sent_via', models.CharField(default='SMTP', max_length=50, verbose_name='sent via')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
            ],
            options={
                'verbose_name': 'email log',
                'verbose_name_plural': 'email logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('enrollment_confirmation', 'Enrollment Confirmation'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('new_lesson', 'New Lesson'), ('course_announcement', 'Course Announcement'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('course_completion', 'Course Completion'), ('reminder', 'Reminder')], max_length=50, unique=True, verbose_name='template type')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('html_content', models.TextField(help_text='Use {{variable}} for dynamic content', verbose_name='HTML content')),
                ('text_content', models.TextField(help_text='Plain text version', verbose_name='text content')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('course_update', 'Course Update'), ('new_lesson', 'New Lesson'), ('announcement', 'Announcement'), ('payment', 'Payment'), ('review', 'Review'), ('achievement', 'Achievement'), ('reminder', 'Reminder'), ('system', 'System')], max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='link URL')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='link text')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('is_sent', models.BooleanField(default=False, verbose_name='sent')),
                ('send_email', models.BooleanField(default=False, verbose_name='send email')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
