# Generated by Django 4.2.7 on 2025-12-15 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_lesson_lesson_type_lessonmedia'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('question', models.TextField(verbose_name='question')),
                ('is_answered', models.BooleanField(default=False, verbose_name='answered')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all students', verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course question',
                'verbose_name_plural': 'course questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('course_update', 'Course Update'), ('new_lesson', 'New Lesson'), ('announcement', 'Announcement'), ('payment', 'Payment'), ('review', 'Review'), ('achievement', 'Achievement'), ('reminder', 'Reminder'), ('system', 'System'), ('message', 'Message'), ('question', 'Question')], max_length=20, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='answer')),
                ('is_best_answer', models.BooleanField(default=False, verbose_name='best answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='notifications.coursequestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'question answer',
                'verbose_name_plural': 'question answers',
                'ordering': ['-is_best_answer', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='courses.course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notifications.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='notificatio_sender__b8b977_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_00d7f3_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_5f59a5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='coursequestion',
            index=models.Index(fields=['course', '-created_at'], name='notificatio_course__cb2cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequestion',
            index=models.Index(fields=['student', '-created_at'], name='notificatio_student_7bd0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequestion',
            index=models.Index(fields=['is_answered', '-created_at'], name='notificatio_is_answ_778786_idx'),
        ),
    ]
