# Generated by Django 5.2.9 on 2026-01-29 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_coursequestion_alter_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('course_update', 'Course Update'), ('new_lesson', 'New Lesson'), ('announcement', 'Announcement'), ('payment', 'Payment'), ('review', 'Review'), ('achievement', 'Achievement'), ('reminder', 'Reminder'), ('system', 'System'), ('message', 'Message'), ('question', 'Question'), ('course_assignment', 'Course Assignment')], max_length=20, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('notification_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('course_update', 'Course Update'), ('new_lesson', 'New Lesson'), ('announcement', 'Announcement'), ('payment', 'Payment'), ('review', 'Review'), ('achievement', 'Achievement'), ('reminder', 'Reminder'), ('system', 'System'), ('message', 'Message'), ('question', 'Question'), ('course_assignment', 'Course Assignment')], max_length=20, verbose_name='type')),
                ('target_role', models.CharField(choices=[('all', 'All Users'), ('student', 'Students'), ('teacher', 'Teachers'), ('admin', 'Platform Admins')], max_length=20, verbose_name='target role')),
                ('send_email', models.BooleanField(default=False, verbose_name='send email')),
                ('send_push', models.BooleanField(default=False, verbose_name='send push')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='action URL')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='recipient count')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='sent count')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='delivered count')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='read count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='failed count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bulk_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bulk notification',
                'verbose_name_plural': 'bulk notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='bulk_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_notifications', to='notifications.bulknotification'),
        ),
    ]
